extraction:
  cpp:
    configure:
      command:
        - GEODE_VERSION=1.13.5
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - wget -O apache-geode.tgz https://downloads.apache.org/geode/${GEODE_VERSION}/apache-geode-${GEODE_VERSION}.tgz
        - tar xzf apache-geode.tgz
        - cmake -DGEODE_ROOT="`pwd`/apache-geode-${GEODE_VERSION}" ..
        - cd dependencies && cmake --build . -- -j2
    index:
      build_command:
        - cd _lgtm_build_dir && cmake --build . --target apache-geode  -- -j 2
  csharp:
    index:
      buildless: true
