extraction:
  cpp:
    configure:
      command:
        - GEODE_VERSION=1.15.0
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - wget -O apache-geode.tgz https://downloads.apache.org/geode/${GEODE_VERSION}/apache-geode-${GEODE_VERSION}.tgz
        - tar xzf apache-geode.tgz
        - "curl -o cmake.tgz -L $(curl -s https://api.github.com/repos/Kitware/CMake/releases | grep -P -i 'browser_download_url.*cmake-\\d+\\.\\d+\\.\\d+-linux-x86_64\\.sh' | head -n 1 | cut -d: -f 2,3 | tr -d \\\")"
        - bash cmake.tgz --skip-license --prefix=`pwd`
        - PATH="`pwd`/bin":$PATH
        - cmake -DGEODE_ROOT="`pwd`/apache-geode-${GEODE_VERSION}" -DCMAKE_INSTALL_PREFIX=/home/build ..
        - cd dependencies && cmake --build . -- -j2
    index:
      build_command:
        - cd _lgtm_build_dir && cmake --build . --target apache-geode  -- -j 2
  csharp:
    index:
      buildless: true
