extraction:
  cpp:
    configure:
      command:
        - GEODE_VERSION=1.13.4
        - CMAKE_VERSION=3.18
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - wget -O apache-geode.tgz https://downloads.apache.org/geode/${GEODE_VERSION}/apache-geode-${GEODE_VERSION}.tgz
        - tar xzf apache-geode.tgz
        - wget -O cmake.tgz https://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.0-Linux-x86_64.tar.gz
        - tar xzf cmake.tgz
        - PATH="`pwd`/cmake-${CMAKE_VERSION}.0-Linux-x86_64/bin":$PATH
        - cmake -DGEODE_ROOT="`pwd`/apache-geode-${GEODE_VERSION}" ..
        - cd dependencies && cmake --build . -- -j2
    index:
      build_command:
        - cd _lgtm_build_dir && cmake --build . --target apache-geode  -- -j 2
  csharp:
    index:
      buildless: true
