book_repo: apache/geode-native/docs/geode-native-book
public_host: localhost

sections:
- repository:
    name: geode-native-docs
  directory: docs/guide-native/11
  subnav_template: geode-nc-nav

template_variables:
  support_url: http://geode.apache.org/community
  product_url: http://geode.apache.org
  book_title: Apache Geode Native Documentation
  support_link: <a href="http://geode.apache.org/community" target="_blank">Community</a>
  support_call_to_action: <a href="http://geode.apache.org/community" target="_blank">Need Help?</a>
  product_link: <div class="header-item"><a href="http://geode.apache.org">Back to Product Page</a></div>
  domain_name: apache.org
  book_title_short: Geode Native Docs

broken_link_exclusions: iefix|using_custom_classes|arrowhead|cppdocs|DotNetDocs|#
